server {
    listen 127.0.0.1:8080;
    client_max_body_size 1000000000;
    # 1) / must answer to GET request ONLY
    location / {
        allow_methods GET;
        root ./;
        index index.html;
        autoindex on;
    }
    # 2) Any file with .bla as extension must answer to POST request by calling the cgi_test executable
    #    The /directory/ location handles this — any .bla file inside will trigger CGI on POST
    location /directory/ {
        allow_methods GET POST;
        root ./YoupiBanane;
        index youpi.bad_extension;
       cgi .bla ./cgi_tester;
    }

    # 3) /post_body must answer anything to POST request with a maxBody of 100
    location /post_body {
        allow_methods POST;
        root ./;
        client_max_body_size 100;
    }
}

