server {
    listen 127.0.0.1:8080;
    listen 0.0.0.0:8081;
    # listen 9090;
    # listen 9090; # errors
    # listen localhost 999; # error
# //TODO only handle ip:port pair
    client_max_body_size 1M;
    error_page 404 ./errors/404.html;
    error_page 500 ./errors/500.html;
    error_page 403 ./errors/403.html;
    #  location /html {
    #     return 301 http://example.org;
    # } 
    # context => 
   location / {
        root ./;
        index  index.html  ;
        autoindex on;
        allow_methods GET POST DELETE;
        cgi .php /usr/bin/php-cgi;
        cgi .py /usr/bin/python;
    }
# directives => root
    location /only-post/ {
         root ./var/www/postonly;
        index post.html;
        allow_methods POST;
        client_max_body_size 5M;
    }

    
 # ";" it doesn't give erroe
   
#locations must always has slash at the end
    location /html2/{
        root ./ ;
        index index.py index.html;
         upload_store ./;
         cgi .py /usr/bin/python;
        allow_methods POST GET;
    }
   
    location /post/ml/ {
        root ./;
        index index.html;
        upload_store ./uploads;
        allow_methods POST GET;
    }

    location /auto {
        root /var/www/auto;
        autoindex on;
        allow_methods GET;
    }
}

# => default => index.html
# ///to do (test folder not in the server files or folders)
# /test
#     location /test {
#         root /var/www/auto/test;
#         index index.py;
#         autoindex on;
#         allow_methods GET;
#     }

